name: Pipeline CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List files (opcional)
        run: ls -R

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint

      - name: Simular Build (opcional)
        run: echo "Build realizado com sucesso!"

      - name: Upload Artifact (opcional)
        uses: actions/upload-artifact@v4
        with:
          name: projeto-codigo
          path: '.'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact (se você fez upload no build)
        uses: actions/download-artifact@v4
        with:
          name: projeto-codigo
          path: .

      - name: Simulando Deploy
        run: echo "Deploy realizado com sucesso!"